### ISSUE TITLE
cdk deploy fails due to stack using assets

### ISSUE THREAD

**Issue by marius-turtle** [aws-samples/lambda-web-scraper-example#3]
Following along the README I tried to deploy the template to an AWS-account after using

`cdk bootstrap aws://my_id/us_east_2`

which ended up in 
```
 ⏳  Bootstrapping environment aws://my_id/us-east-2...
 ✅  Environment aws://my_id/us-east-2 bootstrapped (no changes).
```

but the `cdk deploy` ended up like this

```
❯ cdk deploy 
 ❌  lambdaapp failed: Error: This stack uses assets, so the toolkit stack must be deployed to the environment (Run "cdk bootstrap aws://unknown-account/unknown-region")
    at Object.addMetadataAssetsToManifest (/home/mhi/.nvm/versions/node/v14.16.0/lib/node_modules/aws-cdk/lib/assets.ts:27:11)
    at Object.deployStack (/home/mhi/.nvm/versions/node/v14.16.0/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:211:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at CdkToolkit.deploy (/home/mhi/.nvm/versions/node/v14.16.0/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:180:24)
    at initCommandLine (/home/mhi/.nvm/versions/node/v14.16.0/lib/node_modules/aws-cdk/bin/cdk.ts:208:9)
This stack uses assets, so the toolkit stack must be deployed to the environment (Run "cdk bootstrap aws://unknown-account/unknown-region")
```

Is that due to a wrong region that was chosen? The AWS Account ID I took from the `My Security Credentials` section in the AWS Management Console.

**Comment by kafka399** [comment]
Hi Marius,
You can verify on S3 if a bucket in the given region was created. Are you sure that AWS CLI works fine? E.g. `aws s3 ls` returns a list of bucket in your account?
